name: obratka-web-dev

services:
  webapi-db:
    image: postgres:16-alpine
    container_name: obratka-webapi-db
    environment:
      POSTGRES_DB: obratka_webapi
      POSTGRES_USER: obratka
      POSTGRES_PASSWORD: obratka_dev
    ports:
      - "5432:5432"
    volumes:
      - webapi_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U obratka -d obratka_webapi"]
      interval: 5s
      timeout: 3s
      retries: 10

  seq:
    image: datalust/seq:latest
    container_name: obratka-seq
    environment:
      ACCEPT_EULA: "Y"
    ports:
      - "5341:80"
    volumes:
      - seq_data:/data

volumes:
  webapi_db_data:
  seq_data:
